package View;

import Controller.ControllerMenuPrincipal;
import Model.Conta;
import Model.Usuario;
import javax.swing.JButton;

public class MenuPrincipal extends javax.swing.JFrame {

    ControllerMenuPrincipal controlador;
    public Usuario usuario;
    Conta conta;
    
    public MenuPrincipal() {
        
        
        initComponents();
        this.controlador = new ControllerMenuPrincipal(this); //Instaciando o controlador
        //this.controlador.trazerConta(conta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSaque = new javax.swing.JButton();
        jButtonSaldo = new javax.swing.JButton();
        jButtonExtrato = new javax.swing.JButton();
        jButtonDeposito = new javax.swing.JButton();
        jLabelImagem = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelMenuPrincipal = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabelData = new javax.swing.JLabel();
        jLabelData2 = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabel1U = new javax.swing.JLabel();
        jLabelConta = new javax.swing.JLabel();
        jLabel2C = new javax.swing.JLabel();
        jButtonTransferencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BankFacil menu principal    Fernandes");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonSaque.setBackground(new java.awt.Color(0, 102, 102));
        jButtonSaque.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSaque.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSaque.setText("Saque");
        jButtonSaque.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255)));
        jButtonSaque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaqueActionPerformed(evt);
            }
        });

        jButtonSaldo.setBackground(new java.awt.Color(0, 102, 102));
        jButtonSaldo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSaldo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSaldo.setText("Saldo");
        jButtonSaldo.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255)));
        jButtonSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaldoActionPerformed(evt);
            }
        });

        jButtonExtrato.setBackground(new java.awt.Color(0, 102, 102));
        jButtonExtrato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExtrato.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExtrato.setText("Extrato");
        jButtonExtrato.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255)));
        jButtonExtrato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExtratoActionPerformed(evt);
            }
        });

        jButtonDeposito.setBackground(new java.awt.Color(0, 102, 102));
        jButtonDeposito.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDeposito.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeposito.setText("Depósito");
        jButtonDeposito.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255)));
        jButtonDeposito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepositoActionPerformed(evt);
            }
        });

        jLabelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/FormatFactoryPara a alegria dos pequenos e dosgrandes!.png"))); // NOI18N
        jLabelImagem.setText("jLabel1");

        jButtonSair.setBackground(new java.awt.Color(255, 102, 102));
        jButtonSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSair.setText("Sair");
        jButtonSair.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 153), java.awt.Color.white));
        jButtonSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));

        jLabelMenuPrincipal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMenuPrincipal.setText("Menu Principal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabelMenuPrincipal)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabelMenuPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabelData.setForeground(new java.awt.Color(255, 255, 255));

        jLabelData2.setForeground(new java.awt.Color(255, 255, 255));

        jLabelUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUser.setText("Fernandes");

        jLabel1U.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1U.setText("Usuário:");

        jLabelConta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConta.setText("0");

        jLabel2C.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2C.setText("Nº Conta:");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1U)
                    .addComponent(jLabel2C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabelConta)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabelUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 435, Short.MAX_VALUE)
                        .addComponent(jLabelData2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelData2)
                        .addComponent(jLabelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUser)
                            .addComponent(jLabel1U))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelConta)
                            .addComponent(jLabel2C))))
                .addContainerGap())
        );

        jButtonTransferencia.setBackground(new java.awt.Color(0, 102, 102));
        jButtonTransferencia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonTransferencia.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTransferencia.setText("Transferência");
        jButtonTransferencia.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255)));
        jButtonTransferencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTransferencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaldoActionPerformed
       controlador.navegarParaSaldo();
       controlador.bloquear();
    }//GEN-LAST:event_jButtonSaldoActionPerformed

    private void jButtonDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepositoActionPerformed
       controlador.navegarParaDeposito();
       controlador.bloquear();
    }//GEN-LAST:event_jButtonDepositoActionPerformed

    private void jButtonSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaqueActionPerformed
       controlador.navegarParaSaque();
       controlador.bloquear();
    }//GEN-LAST:event_jButtonSaqueActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
       controlador.sair();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExtratoActionPerformed
       controlador.navegarParaExtrato();
       controlador.bloquear();
    }//GEN-LAST:event_jButtonExtratoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       // Método especial que executa assim que a tela é instanciada
       controlador.data();
       controlador.hora();
       controlador.trazerConta(conta);
    }//GEN-LAST:event_formWindowOpened

    private void jButtonTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransferenciaActionPerformed
        controlador.navegarParaTransferencia();
        controlador.bloquear();
    }//GEN-LAST:event_jButtonTransferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeposito;
    private javax.swing.JButton jButtonExtrato;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSaldo;
    private javax.swing.JButton jButtonSaque;
    private javax.swing.JButton jButtonTransferencia;
    private javax.swing.JLabel jLabel1U;
    private javax.swing.JLabel jLabel2C;
    private javax.swing.JLabel jLabelConta;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelData2;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelMenuPrincipal;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanel1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonDeposito() {
        return jButtonDeposito;
    }

    public void setjButtonDeposito(JButton jButtonDeposito) {
        this.jButtonDeposito = jButtonDeposito;
    }

    public JButton getjButtonExtrato() {
        return jButtonExtrato;
    }

    public void setjButtonExtrato(JButton jButtonExtrato) {
        this.jButtonExtrato = jButtonExtrato;
    }

    public JButton getjButtonSaque() {
        return jButtonSaque;
    }

    public void setjButtonSaque(JButton jButtonSaque) {
        this.jButtonSaque = jButtonSaque;
    }

    public JButton getjButtonSaldo() {
        return jButtonSaldo;
    }

    public void setjButtonSaldo(JButton jButtonSaldo) {
        this.jButtonSaldo = jButtonSaldo;
    }

    public javax.swing.JLabel getjLabelData2() {
        return jLabelData2;
    }

    public void setjLabelData2(javax.swing.JLabel jLabelData) {
        this.jLabelData2 = jLabelData2;
    }

    public javax.swing.JLabel getjLabelData() {
        return jLabelData;
    }

    public javax.swing.JButton getjButtonSair() {
        return jButtonSair;
    }
    
    public javax.swing.JButton getjButtonTransferencia() {
        return jButtonTransferencia;
    }
    
    public void trazerUsuario(Usuario usuario){
        this.usuario = usuario;
        this.jLabelUser.setText(usuario.getNome().toUpperCase());
    }
    
    public void trazerConta(Conta conta){
        this.conta = conta;
        this.jLabelConta.setText(conta.getId()+"");
    }
}

